@startuml
start
: Показать выбор профилей
----
Пользователь:
- выбирает профиль
- добавляет новое лекарство;

if (Есть активный курс лечения?) then (да)
: Показать ближайший прием лекарств;
else (нет)
: Запустить опрос;
: Поиск подходящей болезни;
: Показать подходящие болезни
----
Пользователь выбирает болезнь, которую будет лечить;
: Показать курс лечения;

if (Все лекарства есть?) then
else (нет)
: Показать список для покупки лекарств;
endif

endif

end
@enduml