@startuml base
skinparam classAttributeIconSize 0


class КурсЛечения {

}

class ПриемЛекарства {
    + когда: time
    + сколько: int
}
КурсЛечения "1" --> "n, +списокПриемов" ПриемЛекарства

class Лекарство {
    + название: string
}
ПриемЛекарства "n" --> "1, +лекарство" Лекарство

class Болезнь {
    + название
}
Болезнь "1" --> "1, +курсЛечения" КурсЛечения
Болезнь "1" --> "1, +диагностика" Вопрос

class Вопрос {
    + формулировка: string
}

class Ответ {
    + значение: string
}
Вопрос "1" --> "0..1, +ответ" Ответ

@enduml