@startuml base
skinparam classAttributeIconSize 0


class Приложение <<main, injector>> {
    + {static} main()
    # build() : ПомощникПоЛечению
}
class Приложение #aliceblue
note top
В системе может быть еще один тип ответа - несколько из многих вариантов
end note
Приложение ..> ПомощникПоЛечению : <<create>>

class Болезнь {
}
Болезнь "1" --> "10, +диагностика" Вопрос
ПомощникПоЛечению "1" --> "n, +известныеБолезни" Болезнь

class Вопрос {
}
ПомощникПоЛечению "1" --> "10, +опрос" Вопрос

class Ответ {
}
class Ответ {
}
Вопрос "1" --> "0..1, +ответ" Ответ

class ОтветНесколькоИзМногих {
    + значение: list[string]
}
ОтветНесколькоИзМногих --|> Ответ

class ОтветНесколькоИзМногих #aliceblue
class ПомощникПоЛечению #red
class Вопрос #red
class Болезнь #red


@enduml