@startuml base
skinparam classAttributeIconSize 0


class Приложение <<main, injector>> {
    + {static} main()
    # build() : ПомощникПоЛечению
}
note top
В системе может быть еще один тип ответа - несколько из многих вариантов
end note


class ОтветНесколькоИзМногих {
    + значение: list[string]
    + сравнить(другойОтвет: Ответ): boolean
    + сравнить(другойОтвет: ОтветНесколькоИзМногих): boolean
}
ОтветНесколькоИзМногих --|> Ответ



class ВопросНесколькоИзМногих {
    - формулировкаВариантов: list[string]
    + on_введеноЗначение(значение: list[string])
    + отобразить()
}
ВопросНесколькоИзМногих --|> Вопрос
ВопросНесколькоИзМногих ..> ОтветНесколькоИзМногих: <<create>>
Приложение ..> ВопросНесколькоИзМногих: <<create>>


class Приложение #aliceblue
class ОтветНесколькоИзМногих #aliceblue
class ВопросНесколькоИзМногих #aliceblue



@enduml