@startuml base

class Приложение <<main, injector>> {
    + {static} main()
    # build(): АвтоматПоПриготовлениюНапитков
}
Приложение ..> АвтоматПоПриготовлениюНапитков: <<create>>
Приложение ..> ПриемникДенег: <<create>>
Приложение ..> Mеню: <<create>>


class АвтоматПоПриготовлениюНапитков {
    + состояниеАвтомата

    + run()
    + показатьОсновнойЭкран()
    + показатьЭкранГотовогоНапитка()

    # on_добавленаКупюра(номинал: string)
    # on_выбранНапиток(название: string)
    # on_забратьНапиток()

    # проверитьХватаетЛиДенег(выбранныеРецепт: Рецепт): boolean
    # проверитьХватаетИнгредиентов(выбранныеРецепт: Рецепт): boolean
    # приготовитьНапиток(выбранныеРецепт: Рецепт)
}
АвтоматПоПриготовлениюНапитков "1" -> "1, +меню" Mеню
АвтоматПоПриготовлениюНапитков "1" -> "1, +приемникДенег" ПриемникДенег
АвтоматПоПриготовлениюНапитков "1" -> "0..1, +готовыйНапиток" Рецепт
АвтоматПоПриготовлениюНапитков "1" -> "n, +резервуарыИнгредиенту" Резервуар

class Рецепт {
    + название: string
    + стоимость: int
}
Рецепт "1" --> "n, +ингредиент" Ингредиент
(Рецепт, Ингредиент) .. ИнгредиентMap
class ИнгредиентMap {
    + количество: int
}

class ПриемникДенег {
    + внесенныеДеньги : int

    + добавитьДенег(номинал: int)
}

class Mеню {
}
Mеню "1" --> "n, +напитки" Рецепт


class Резервуар {
    + количество : int
}

class Ингредиент {
    + название: string
}

Резервуар "1" --> "1, +ингредиент"  Ингредиент

' Автомат по приготовлению напитков (автомат) готовит напиток по рецепту из имеющихся в нем ингредиентов и продает покупателю. 
' На передней панели автомата расположен модуль приема денег с отображением внесенных и не потраченных денег, 
' меню выбора напитка и модуль выдачи готового напитка. Для приготовления напитка покупатель вносит деньги автомату, затем выбирает напиток, ждет когда автомат приготовит напиток, затем забирает его. 
' Ингредиенты хранятся в резервуарах. 
' Перед приготовление выбранного напитка автомат проверяет есть ли нужное количество ингредиента в его резервуаре. 
' Если какого-то ингредиента не хватает, автомат сообщает об этом покупателю. 
' Если в процессе работы автомата произошел сбой, то автомат переходит в состояние требующие сервисного обслуживания. 
' Приготовление напитков возможно только в рабочем состоянии автомата.
' Для пополнения ингредиентов приходит обслуживающий персонал. 
' Он переводит автомат в состояние сервисного обслуживания, открывает автомат и пополняет резервуары ингредиентами.
' Автомат может приготовить три напитка: кофе, кофе с молоком и горячий шоколад. 

@enduml