@startuml
actor Покупатель
boundary UI

Приложение -> Приложение: build
Приложение -> АвтоматПоПриготовлениюНапитков: run
АвтоматПоПриготовлениюНапитков -> АвтоматПоПриготовлениюНапитков: показатьОсновнойЭкран()
АвтоматПоПриготовлениюНапитков --> АвтоматПоПриготовлениюНапитков

== Автомат готов к работе ==

Покупатель --> UI: добавить купюру в приемник купюр 
UI -> АвтоматПоПриготовлениюНапитков: on_добавленаКупюра()
АвтоматПоПриготовлениюНапитков -> ПриемникДенег: добавитьДенег()
АвтоматПоПриготовлениюНапитков <-- ПриемникДенег
UI <-- АвтоматПоПриготовлениюНапитков

Покупатель --> UI: добавить купюру в приемник купюр
UI -> АвтоматПоПриготовлениюНапитков: on_добавленаКупюра()
АвтоматПоПриготовлениюНапитков -> ПриемникДенег: добавитьДенег()
АвтоматПоПриготовлениюНапитков <-- ПриемникДенег
UI <-- АвтоматПоПриготовлениюНапитков

Покупатель --> UI: выбрать напиток в меню
UI -> АвтоматПоПриготовлениюНапитков: on_выбранНапиток

АвтоматПоПриготовлениюНапитков -> АвтоматПоПриготовлениюНапитков: проверитьХватаетЛиДенег()
АвтоматПоПриготовлениюНапитков --> АвтоматПоПриготовлениюНапитков

АвтоматПоПриготовлениюНапитков -> АвтоматПоПриготовлениюНапитков: проверитьХватаетИнгредиентов()
АвтоматПоПриготовлениюНапитков --> АвтоматПоПриготовлениюНапитков

== Приготовление напитка ==

АвтоматПоПриготовлениюНапитков -> АвтоматПоПриготовлениюНапитков: приготовитьНапиток()
АвтоматПоПриготовлениюНапитков --> АвтоматПоПриготовлениюНапитков

АвтоматПоПриготовлениюНапитков -> АвтоматПоПриготовлениюНапитков: показатьЭкранГотовогоНапитка()
АвтоматПоПриготовлениюНапитков --> АвтоматПоПриготовлениюНапитков
UI <-- АвтоматПоПриготовлениюНапитков

Покупатель --> UI: забрать напиток
UI -> АвтоматПоПриготовлениюНапитков: on_забратьНапиток()
UI <-- АвтоматПоПриготовлениюНапитков

@enduml